export const elements = {
    setTimer: document.querySelector('#set-time'),
    displayTimer: document.querySelector('#clock'),
    startTimer: document.querySelector('#start-timer'),
    resumeTimer: document.querySelector('#resume-timer'),
    stopTimer: document.querySelector('#stop-timer'),
    homeScoreDisplay: document.querySelector('#score-home'),
    homePlus1: document.querySelector('#home-plus-1'),
    homeMinus1: document.querySelector('#home-minus-1'),
    awayScoreDisplay: document.querySelector('#score-away'),
    awayPlus1: document.querySelector('#away-plus-1'),
    awayMinus1: document.querySelector('#away-minus-1'),
    periodDisplay: document.querySelector('#period-display'),
    periodSet: document.querySelector('#period-set'),
    homeBonus: document.querySelector('#home-bonus'),
    awayBonus: document.querySelector('#away-bonus'),
    homeBonusDisplay: document.querySelector('#home-bonus-display'),
    awayBonusDisplay: document.querySelector('#away-bonus-display'),
    homePossession: document.querySelector('#home-possession'),
    awayPossession: document.querySelector('#away-possession'),
    homePossessionDisplay: document.querySelector('#home-possession-display'),
    awayPossessionDisplay: document.querySelector('#away-possession-display'),
    reset: document.querySelector('#reset')
};